# 20 Most spoken languages in the world
ENGLISH = "en"
CHINESE = "zh"
HINDI = "hi"
SPANISH = "es"
FRENCH = "fr"
BENGALI = "bn"
RUSSIAN = "ru"
PORTUGUESE = "pt"
INDONESIAN = "id"
ARABIC = "ar"
URDU = "ur"
JAPANESE = "ja"
DEUTSCH = "de"
#PANJABI = "pa" # No translation model
JAVANESE = "jv"
TELUGU = "te"
TURKISH = "tr"
#KOREAN = "ko" # No good translation models
MARATHI = "mr"

# other european languages
ITALIAN = "it"
ROMANIAN = "ro"
SWEDISH = "sv"
FINNISH = "fi"
DUTCH = "nl"
UKRAINIAN = "uk"
POLISH = "pl"
DANISH = "da"
BULGARIAN = "bg"
CZECH = "cs"
GREEK = "el"
ICELANDIC = "is"
#NORWEGIAN = "no" # No translation model available
CROATIAN = "hr"
HUNGARIAN = "hu"
SLOVENIAN = "sl"
LITHUANIAN = "lt"
ALBANIAN = "sq"
ESTONIAN = "et"
BELARUSIAN = "be"
SERBIAN = "sr"
GEORGIAN = "ka"
MACEDONIAN = "mk"
#BOSNIAN = "bs" No translation model
SLOVAK = "sk"
AZERBAIJANI = "az"
ARMENIAN = "hy"

# Spanish co-oficial languages
CATALAN = "ca"
GALICIAN = "gl"
BASQUE = "eu"

# Other asiatic languages
#PERSIAN = "fa" # No translation model
VIETNAMESE = "vi"
THAI = "th"
#NEPALI = "ne" # No translation model
LINGALA = "ln"
HAITIAN = "ht"
MONGOLIAN = "mn"

# African languages
AFRIKAANS = "af"
SWAHILI = "sw"
TAMIL = "ta"
HEBREW = "he"
MALAYALAM = "ml"
YORUBA = "yo"
LATVIAN = "lv"
KANNADA = "kn"
WELSH = "cy"
HAUSA = "ha"
XHOSA = "xh"
IGBO = "ig"
TAGALOG = "tl"
AMHARIC = "am"
SOMALI = "so"
KINYARWANDA = "rw"
MALTESE = "mt"
SHONA = "sn"
GANDA = "lg"
MALAGASY = "mg"
ZULU = "zu"
SAMOAN = "sm"
