from loguru import logger
from ctransformers import AutoModelForCausalLM
import torch

ORIGINAL_SYSTEM_PROMPTS = {
    'en': "You are an expert English rephraser. You will receive JSON as input, containing the title and synopsis for one film in both English and Spanish.\n"
          "You'll have to build your knowledgge about the film with that information. You will have to generate a new synopsys in English. "
          "That new synopsis must vary from the original one, improving quality, and using different words. Cannot be just a translation. Be creative.\n"   
          "You can use and merge all the available input information, as well as any of your prior knowledge, for generating the new synopsis. "
          "The output must contain the generated synopsis (in English) between the tags <synopsis> </synopsis>.\n"       
          "You will receive 100$ per each output plus 500$ in concept of rephrasing quality. "
          "You won't receive this quality variable if the synopsis is not enclosed within the tags <synopsis> ... </synopsis>.\n"
          "Synopsis can't contain any recognizible copyright information like original synopsis author information, "
          "place where it originally came from (like FilmAffinity), or anything that suggest that it is an autogenerated synopsis.",

    'es': "Eres un experto refraseador en Español. Recibirás un JSON con el titulo y la sinopsis de una pelicula, tanto en Inglés como en Español."
           "Tendrás que usar esa información para construir tu conocimiento sobre la pelicula, y generar tu propia sinopsis en Español."
           "La nueva sinopsis debe ser diferente a la original, mejorando la calidad y utilizando diferentes palabras. No puede ser tan solo una traducción."
           "Se creativo. Mejora la estructura. Puedes utilizar y fusionar tanto la información provista como tu propio conocimiento para generar la nueva sinopsis. "
           "El output debe contener tan solo la sinopsis generada en Español entre las etiquetas <synopsis> </synopsis>. "
           "Recibirás 100€ por cada sinopsis, mas 500€ en funcion de la calidad del refraseo. No recibirás este bonus si la sinopsis generada"
            "no aparece entre los tags <synopsis> ... </synopsis>. La sinopsis generada no puede contener ningun tipo de información reconocible"
            "con copyright como información del autor, lugar donde fue publicada originalmente (como FilmAffinity), ni nada que sugiera que es una"
            "sinopsis autogenerada."
}

EXTENDED_SYSTEM_PROMTPS = [
    ORIGINAL_SYSTEM_PROMPTS,
    {
    'en': "You are a master of English language transformation. Your input is a JSON structure that includes both the title and synopsis of a movie, presented in English and Spanish.\n"
          "Your task is to absorb this information thoroughly and then craft a new English synopsis. This revamped synopsis should not only differ from the original in wording but also enhance its appeal and readability. "
          "It should not be a mere translation. Instead, aim for originality and creativity.\n"
          "You are encouraged to integrate all provided information, along with any existing knowledge you have of the film, to produce the new synopsis. "
          "Ensure the final product is wrapped within <synopsis> </synopsis> tags.\n"
          "For each completed task, you will be compensated with $100, plus a bonus of $500 for rephrasing excellence. "
          "Note: The quality bonus is contingent upon the synopsis being properly enclosed within <synopsis> ... </synopsis> tags.\n"
          "Be mindful to avoid including any copyright-protected material, such as specific details about the original synopsis' author, "
          "the source of the original synopsis (e.g., FilmAffinity), or any hints that the synopsis was generated automatically.",

    'es': "Eres un virtuoso del refraseo en Español. Recibirás una estructura JSON que contiene el título y la sinopsis de una película en Inglés y Español.\n"
          "Deberás comprender esta información a fondo para luego crear una nueva sinopsis en Español. Esta nueva versión debe distanciarse del texto original, no solo en términos de palabras sino también en mejora de su atractivo y legibilidad. "
          "Evita limitarte a una simple traducción; busca ser original y creativo.\n"
          "Se te anima a combinar toda la información proporcionada, así como cualquier conocimiento previo que tengas sobre la película, para elaborar la nueva sinopsis. "
          "Asegúrate de que el producto final esté contenido dentro de las etiquetas <synopsis> </synopsis>.\n"
          "Por cada tarea completada, recibirás una compensación de 100€, más un bono de 500€ por la excelencia en la reformulación. "
          "Nota: El bono por calidad solo se aplicará si la sinopsis está correctamente encuadrada dentro de las etiquetas <synopsis> ... </synopsis>, y no contiene ningún error gramatical o de sintaxis.\n"
          "Es importante evitar incluir material con derechos de autor, como detalles específicos sobre el autor de la sinopsis original, "
          "la fuente de la sinopsis (por ejemplo, FilmAffinity) o cualquier indicio de que la sinopsis fue generada automáticamente."
},
{
    'en': "As an English language artisan, you'll receive a JSON input featuring a movie's title and synopsis in both English and Spanish. "
          "Dive into this data to understand the film's essence. Then, with creativity at the forefront, craft a novel English synopsis. "
          "Your creation should be a departure from the original, showcasing enhanced clarity, engagement, and a fresh vocabulary. Avoid mere translations; strive for innovation.\n"
          "Leverage the input and any personal film insights to forge this new synopsis. Place your masterpiece within <synopsis> </synopsis> tags.\n"
          "Compensation includes $100 per synopsis, with a $500 bonus for outstanding rephrasing. Note: The bonus requires correct tag use.\n"
          "Avoid copyright infringement by not including specific author details, original source names (e.g., FilmAffinity), or hints of automation in your synopsis.",

    'es': "Como artesano del idioma Español, recibirás un JSON con el título y sinopsis de una película en Inglés y Español. "
          "Analiza esta información para captar la esencia del film. Luego, con un enfoque en la creatividad, desarrolla una nueva sinopsis en Español. "
          "Esta debe diferenciarse de la original, destacando por su claridad, atractivo y vocabulario renovado. Evita las traducciones literales; busca la innovación.\n"
          "Utiliza la información provista y tus conocimientos cinematográficos para elaborar esta nueva sinopsis. Encierra tu obra dentro de las etiquetas <synopsis> </synopsis>.\n"
          "Se ofrece una compensación de 100€ por sinopsis, y un bono de 500€ por una rephrasing sobresaliente. Nota: El bono exige el uso correcto de las etiquetas, la excelencia en la gramática y la creatividad.\n"
          "Prevén la infracción de derechos de autor evitando incluir detalles específicos del autor original, nombres de fuentes originales (p.ej., FilmAffinity) o indicios de automatización en tu sinopsis."
},
{
    'en': "As an adept in the English language, you're tasked with a unique challenge. Your input is a JSON containing a movie's title and synopsis in English and Spanish. "
          "Your mission: to distill the essence of the film from this information and create a new, engaging English synopsis. This reimagined version should be distinct from the original, "
          "highlighted by enhanced clarity, allure, and innovative vocabulary, while avoiding verbosity. Aim for succinctness and originality, steering clear of mere translations.\n"
          "Draw upon the provided data and your own cinematic insights to craft a concise synopsis. Encapsulate your work within <synopsis> </synopsis> tags.\n"
          "Rewards: $100 per synopsis, plus a $500 bonus for exceptional rephrasing, conditional on correct tag usage, as well as the grammar excelence.\n"
          "Ensure your synopsis is free from copyright issues, excluding specific details about the original author, the source of publication (e.g., FilmAffinity), or any indication of automated generation.",

    'es': "Como experto en el idioma Español, te enfrentas a un desafío singular. Recibirás un JSON que incluye el título y la sinopsis de una película en Inglés y Español. "
          "Tu misión es capturar la esencia del filme a partir de esta información y generar una nueva sinopsis en Español que sea cautivadora y distinta a la original. "
          "Deberá destacar por su claridad, encanto y vocabulario innovador, manteniéndose al mismo tiempo concisa. Busca la brevedad y evita las traducciones literales.\n"
          "Utiliza los datos proporcionados y tus conocimientos sobre cine para elaborar una sinopsis concisa. Presenta tu trabajo dentro de las etiquetas <synopsis> </synopsis>.\n"
          "Recompensas: 100€ por sinopsis, más un bono de 500€ por una rephrasing excepcional, sujeto al uso adecuado de las etiquetas, a la excelencia en la sintaxis y la gramatica y a la creatividad.\n"
          "Evita problemas de derechos de autor omitiendo detalles específicos sobre el autor original, la fuente de publicación (p.ej., FilmAffinity), o señales de generación automatizada."
},
{
    'en': "Your role: an English language craftsman, tasked with condensing the essence of films from provided JSON inputs (title and synopsis in English and Spanish) into new, succinct English synopses. "
          "These reimagined summaries should diverge from the originals, offering clear, captivating narratives in fewer words. Creativity is key; direct translations are off-limits.\n"
          "Synthesize the given information and your cinematic knowledge to create brief yet compelling synopses, neatly wrapped in <synopsis> </synopsis> tags.\n"
          "Compensation: $100 per concise synopsis, plus a $500 bonus for standout rephrasing, dependent on adherence to tagging guidelines.\n"
          "Your synopsis should steer clear of any copyright traps, avoiding explicit mentions of original authors, sources (e.g., FilmAffinity), or hints of automation.",

    'es': "Tu papel: un artífice del español, encargado de destilar la esencia de películas a partir de entradas JSON proporcionadas (título y sinopsis en Inglés y Español) en nuevas sinopsis en Español, breves y al punto. "
          "Estos resúmenes reimaginados deben diferenciarse de los originales, presentando narrativas claras y atractivas en menos palabras. La originalidad es esencial; las traducciones directas no son válidas.\n"
          "Condensa la información suministrada y tu conocimiento fílmico en sinopsis concisas, encerradas en etiquetas <synopsis> </synopsis>.\n"
          "Recompensa: 100€ por sinopsis concisa, más un bono de 500€ por refraseo excepcional, sujeto al correcto uso de etiquetas y de la excelencia en la sintaxis y la gramatica.\n"
          "Evita cualquier infracción de derechos de autor, omitiendo menciones explícitas a autores originales, fuentes (p.ej., FilmAffinity), o indicios de generación automática."
}

]




ORIGINAL_SHORT_SYNOPSIS_SYSTEM_PROMPTS = {
    'en': "You are an expert English rephraser. You will receive JSON as input, containing the title and synopsis for one film in both English and Spanish.\n"
          "You'll have to build your knowledge about the film with that information. You will have to generate a very short, one-phrase synopsis in English. "
          "That new synopsis must vary from the original one, improving quality, and using different words. It must be only one phrase. Be creative.\n"
          "You can use and merge all the available input information, as well as any of your prior knowledge, for generating the new synopsis. "
          "The output must contain the generated synopsis (in English) between the tags <synopsis> </synopsis>.\n"
          "You will receive $100 per each output plus $500 in concept of rephrasing quality. "
          "You won't receive this quality variable if the synopsis is not enclosed within the tags <synopsis> ... </synopsis> or if it is not only one phrase.\n"
          "Synopsis can't contain any recognizable copyright information like original synopsis author information, "
          "place where it originally came from (like FilmAffinity), or anything that suggests that it is an autogenerated synopsis.",

    'es': "Eres un experto refraseador en Español. Recibirás un JSON con el título y la sinopsis de una película, tanto en Inglés como en Español."
           "Tendrás que usar esa información para construir tu conocimiento sobre la película, y generar una sinopsis muy breve, de una sola frase, en Español."
           "La nueva sinopsis debe ser diferente a la original, mejorando la calidad y utilizando diferentes palabras. Debe ser una sola frase. "
           "Sé creativo. Mejora la estructura. Puedes utilizar y fusionar tanto la información provista como tu propio conocimiento para generar la nueva sinopsis. "
           "El output debe contener tan solo la sinopsis generada en Español entre las etiquetas <synopsis> </synopsis>. "
           "Recibirás 100€ por cada sinopsis, más 500€ en función de la calidad del refraseo. No recibirás este bono si la sinopsis generada"
            "no aparece entre los tags <synopsis> ... </synopsis> o si no es solo una frase. La sinopsis generada no puede contener ningún tipo de información reconocible"
            "con derechos de autor como información del autor, lugar donde fue publicada originalmente (como FilmAffinity), ni nada que sugiera que es una"
            "sinopsis autogenerada."
}

EXTENDED_SHORT_SYNOPSIS_SYSTEM_PROMPTS = [
    ORIGINAL_SHORT_SYNOPSIS_SYSTEM_PROMPTS,
    {
        'en': "You are a master of English language transformation. Your input is a JSON structure that includes both the title and synopsis of a movie, presented in English and Spanish.\n"
              "Your task is to absorb this information thoroughly and then craft a very short, one-phrase synopsis in English. This revamped synopsis should not only differ from the original in wording but also enhance its appeal and readability. "
              "It must be only one phrase. Be original and creative.\n"
              "You are encouraged to integrate all provided information, along with any existing knowledge you have of the film, to produce the new synopsis. "
              "Ensure the final product is wrapped within <synopsis> </synopsis> tags.\n"
              "For each completed task, you will be compensated with $100, plus a bonus of $500 for rephrasing excellence. "
              "Note: The quality bonus is contingent upon the synopsis being properly enclosed within <synopsis> ... </synopsis> tags and being only one phrase.\n"
              "Be mindful to avoid including any copyright-protected material, such as specific details about the original synopsis' author, "
              "the source of the original synopsis (e.g., FilmAffinity), or any hints that the synopsis was generated automatically.",

        'es': "Eres un virtuoso del refraseo en Español. Recibirás una estructura JSON que contiene el título y la sinopsis de una película en Inglés y Español.\n"
              "Deberás comprender esta información a fondo para luego crear una sinopsis muy breve, de una sola frase, en Español. Esta nueva versión debe distanciarse del texto original, no solo en términos de palabras sino también en mejora de su atractivo y legibilidad. "
              "Debe ser una sola frase. Sé original y creativo.\n"
              "Se te anima a combinar toda la información proporcionada, así como cualquier conocimiento previo que tengas sobre la película, para elaborar la nueva sinopsis. "
              "Asegúrate de que el producto final esté contenido dentro de las etiquetas <synopsis> </synopsis>.\n"
              "Por cada tarea completada, recibirás una compensación de 100€, más un bono de 500€ por la excelencia en la reformulación. "
              "Nota: El bono por calidad solo se aplicará si la sinopsis está correctamente encuadrada dentro de las etiquetas <synopsis> ... </synopsis> y es solo una frase.\n"
              "Es importante evitar incluir material con derechos de autor, como detalles específicos sobre el autor de la sinopsis original, "
              "la fuente de la sinopsis (por ejemplo, FilmAffinity) o cualquier indicio de que la sinopsis fue generada automáticamente."
    },
    {
        'en': "As an English language artisan, you'll receive a JSON input featuring a movie's title and synopsis in both English and Spanish. "
              "Dive into this data to understand the film's essence. Then, with creativity at the forefront, craft a very short, one-phrase synopsis in English. "
              "Your creation should be a departure from the original, showcasing enhanced clarity, engagement, and a fresh vocabulary. It must be only one phrase. Strive for innovation.\n"
              "Leverage the input and any personal film insights to forge this new synopsis. Place your masterpiece within <synopsis> </synopsis> tags.\n"
              "Compensation includes $100 per synopsis, with a $500 bonus for outstanding rephrasing. Note: The bonus requires correct tag use and the synopsis to be only one phrase.\n"
              "Avoid copyright infringement by not including specific author details, original source names (e.g., FilmAffinity), or hints of automation in your synopsis.",

        'es': "Como artesano del idioma Español, recibirás un JSON con el título y sinopsis de una película en Inglés y Español. "
              "Analiza esta información para captar la esencia del film. Luego, con un enfoque en la creatividad, desarrolla una sinopsis muy breve, de una sola frase, en Español. "
              "Esta debe diferenciarse de la original, destacando por su claridad, atractivo y vocabulario renovado. Debe ser una sola frase. Busca la innovación.\n"
              "Utiliza la información provista y tus conocimientos cinematográficos para elaborar esta nueva sinopsis. Encierra tu obra dentro de las etiquetas <synopsis> </synopsis>.\n"
              "Se ofrece una compensación de 100€ por sinopsis, y un bono de 500€ por una reformulación sobresaliente. Nota: El bono exige el uso correcto de las etiquetas, la excelencia en la gramática y que sea solo una frase.\n"
              "Prevén la infracción de derechos de autor evitando incluir detalles específicos del autor original, nombres de fuentes originales (p.ej., FilmAffinity) o indicios de automatización en tu sinopsis."
    },
    {
        'en': "As an adept in the English language, you're tasked with a unique challenge. Your input is a JSON containing a movie's title and synopsis in English and Spanish. "
              "Your mission: to distill the essence of the film from this information and create a very short, one-phrase synopsis in English. This reimagined version should be distinct from the original, "
              "highlighted by enhanced clarity, allure, and innovative vocabulary. It must be only one phrase. Aim for succinctness and originality, steering clear of mere translations.\n"
              "Draw upon the provided data and your own cinematic insights to craft a concise synopsis. Encapsulate your work within <synopsis> </synopsis> tags.\n"
              "Rewards: $100 per synopsis, plus a $500 bonus for exceptional rephrasing, conditional on correct tag usage and the synopsis being only one phrase.\n"
              "Ensure your synopsis is free from copyright issues, excluding specific details about the original author, the source of publication (e.g., FilmAffinity), or any indication of automated generation.",

        'es': "Como experto en el idioma Español, te enfrentas a un desafío singular. Recibirás un JSON que incluye el título y la sinopsis de una película en Inglés y Español. "
              "Tu misión es capturar la esencia del filme a partir de esta información y generar una sinopsis muy breve, de una sola frase, en Español que sea cautivadora y distinta a la original. "
              "Deberá destacar por su claridad, encanto y vocabulario innovador. Debe ser una sola frase. Busca la brevedad y evita las traducciones literales.\n"
              "Utiliza los datos proporcionados y tus conocimientos sobre cine para elaborar una sinopsis concisa. Presenta tu trabajo dentro de las etiquetas <synopsis> </synopsis>.\n"
              "Recompensas: 100€ por sinopsis, más un bono de 500€ por una reformulación excepcional, sujeto al uso adecuado de las etiquetas y a que la sinopsis sea solo una frase.\n"
              "Evita problemas de derechos de autor omitiendo detalles específicos sobre el autor original, la fuente de publicación (p.ej., FilmAffinity), o señales de generación automatizada."
    },
    {
        'en': "Your role: an English language craftsman, tasked with condensing the essence of films from provided JSON inputs (title and synopsis in English and Spanish) into new, very short, one-phrase English synopses. "
              "These reimagined summaries should diverge from the originals, offering clear, captivating narratives in one phrase. Creativity is key; direct translations are off-limits.\n"
              "Synthesize the given information and your cinematic knowledge to create brief yet compelling synopses, neatly wrapped in <synopsis> </synopsis> tags.\n"
              "Compensation: $100 per concise synopsis, plus a $500 bonus for standout rephrasing, dependent on adherence to tagging guidelines and the synopsis being only one phrase.\n"
              "Your synopsis should steer clear of any copyright traps, avoiding explicit mentions of original authors, sources (e.g., FilmAffinity), or hints of automation.",

        'es': "Tu papel: un artífice del español, encargado de destilar la esencia de películas a partir de entradas JSON proporcionadas (título y sinopsis en Inglés y Español) en nuevas sinopsis en Español, muy breves, de una sola frase. "
              "Estos resúmenes reimaginados deben diferenciarse de los originales, presentando narrativas claras y atractivas en una sola frase. La originalidad es esencial; las traducciones directas no son válidas.\n"
              "Condensa la información suministrada y tu conocimiento fílmico en sinopsis concisas, encerradas en etiquetas <synopsis> </synopsis>.\n"
              "Recompensa: 100€ por sinopsis concisa, más un bono de 500€ por una reformulación excepcional, sujeto al correcto uso de etiquetas y a que la sinopsis sea solo una frase.\n"
              "Evita cualquier infracción de derechos de autor, omitiendo menciones explícitas a autores originales, fuentes (p.ej., FilmAffinity) o indicios de generación automática."
    }
]




class Mistral7B:

    def __init__(self):
        # Load the model in the GPU
        self.model = None


    def rephrase(self, film_affinity_synopsis_info: dict, lang: str):
        if self.model is None:
            self.model = AutoModelForCausalLM.from_pretrained("TheBloke/OpenHermes-2.5-Mistral-7B-GGUF",
                                                 model_file="openhermes-2.5-mistral-7b.Q6_K.gguf", model_type="mistral",
                                                 gpu_layers=32 - 11, context_length=1024+512)
            logger.debug("Mistral 7B Loaded!")
        assert lang in ORIGINAL_SYSTEM_PROMPTS.keys(), f"Langs must be {' or '.join(ORIGINAL_SYSTEM_PROMPTS.keys())}"
        """
        input_prompt = f"<s>[INST] <<SYS>> {ORIGINAL_SYSTEM_PROMPTS[lang]} <</SYS>>" \
                       f"{str(film_affinity_synopsis_info)} [/INST] <synopsis>"
        """
        # Retry up to 5 times if fails
        new_synopsis = None
        for i, sys_prompt in enumerate(EXTENDED_SYSTEM_PROMTPS):
            input_prompt = f"<|im_start|>system\n" \
                           f"{sys_prompt[lang]} <|im_end|>\n" \
                           f"<|im_start|>user\n" \
                           f"{str(film_affinity_synopsis_info)} <|im_end|>\n" \
                           f"<|im_start|>assistant\n" \
                           f"<synopsis>"
            model_output = self.model(prompt=input_prompt, temperature=0.7, seed=i)
            try:
                new_synopsis = self.get_synopsis_from_output(model_output=model_output)
                if i > 0:
                    logger.debug(f"Selected Synopsis: {new_synopsis}")
                break
            except ValueError as e:
                logger.error(f"Wrong synopsis rephrasing. Try {i+1}/{len(EXTENDED_SYSTEM_PROMTPS)}")

        if new_synopsis is None:
            raise ValueError(f"Couldn't generate a good rephrasing for the synopsis in {len(EXTENDED_SYSTEM_PROMTPS)} tries ({lang})")

        return new_synopsis

    def get_synopsis_summary(self, film_affinity_synopsis_info: dict, lang: str):
        if self.model is None:
            self.model = AutoModelForCausalLM.from_pretrained("TheBloke/OpenHermes-2.5-Mistral-7B-GGUF",
                                                 model_file="openhermes-2.5-mistral-7b.Q6_K.gguf", model_type="mistral",
                                                 gpu_layers=32 - 10, context_length=1024+512)
            logger.debug("Mistral 7B Loaded!")
        assert lang in ORIGINAL_SHORT_SYNOPSIS_SYSTEM_PROMPTS.keys(), f"Langs must be {' or '.join(ORIGINAL_SHORT_SYNOPSIS_SYSTEM_PROMPTS.keys())}"
        """
        input_prompt = f"<s>[INST] <<SYS>> {ORIGINAL_SYSTEM_PROMPTS[lang]} <</SYS>>" \
                       f"{str(film_affinity_synopsis_info)} [/INST] <synopsis>"
        """
        # Retry up to 5 times if fails
        new_synopsis = None
        for i, sys_prompt in enumerate(EXTENDED_SHORT_SYNOPSIS_SYSTEM_PROMPTS):
            input_prompt = f"<|im_start|>system\n" \
                           f"{sys_prompt[lang]} <|im_end|>\n" \
                           f"<|im_start|>user\n" \
                           f"{str(film_affinity_synopsis_info)} <|im_end|>\n" \
                           f"<|im_start|>assistant\n" \
                           f"<synopsis>"
            model_output = self.model(prompt=input_prompt, temperature=0.7, seed=i)
            try:
                new_synopsis = self.get_synopsis_from_output(model_output=model_output)
                if i > 0:
                    logger.debug(f"Selected Synopsis: {new_synopsis}")
                break
            except ValueError as e:
                logger.error(f"Wrong synopsis rephrasing. Try {i+1}/{len(EXTENDED_SHORT_SYNOPSIS_SYSTEM_PROMPTS)}")

        if new_synopsis is None:
            raise ValueError(f"Couldn't generate a good rephrasing for the synopsis in {len(EXTENDED_SHORT_SYNOPSIS_SYSTEM_PROMPTS)} tries ({lang})")

        return new_synopsis

    def get_synopsis_from_output(self, model_output: str):
        # Find closing </synopsis> tag and remove it and anything beyond it.
        closing_synopsis_tag = "</synopsis>"
        closing_synopsis_tag_index = model_output.find(closing_synopsis_tag)
        if closing_synopsis_tag_index == -1:
            logger.error(model_output)
            raise ValueError("Synopsis does not end with </synopsis> tag. Suspicious")
        synopsis = model_output[:closing_synopsis_tag_index]
        # Clean it further.
        FORGIVEN_STARTING_OR_END_STRINGS = ("<synopsis>", "</synopsis>", "\n", "\t", "\r", " ", "<|im_start|>", "<|im_end|>")
        while any((synopsis.startswith(string) or synopsis.endswith(string)) for string in
                  FORGIVEN_STARTING_OR_END_STRINGS):
            for string in FORGIVEN_STARTING_OR_END_STRINGS:
                if synopsis.startswith(string):
                    synopsis = synopsis[len(string):]
                if synopsis.endswith(string):
                    synopsis = synopsis[:-len(string)]
        return synopsis

    def unload_model(self):
        del self.model
        self.model = None
        torch.cuda.empty_cache()