import os
from scrapers.constants.FilmAffinity import DATABASES_PATH, STREAMING, BUY, ADS, RENT, FREE

FILMS_DATABASE_JSON_PATH = os.path.join(DATABASES_PATH, "films_database.json")
STORED_IDS_JSON_PATH = os.path.join(DATABASES_PATH, "stored_ids.json")
PENDING_FILMS_JSON_PATH = os.path.join(DATABASES_PATH, "pending_films.json")
DISCARDED_IDS_JSON_PATH = os.path.join(DATABASES_PATH, "discarded_ids.json")

# There are 4 movie info elements ["Technical info", "Ranking", "Awards", "Synopsis"]
MOVIE_INFO_PARENT_ID = "left-column"
MOVIE_INFO_PARENT_ELEMENT = "div"
MOVIE_INFO_CLASS = "movie-info"
MOVIE_INFO_ELEMENT = "dl"

MOVIE_INFO_SECTIONS_XPATH = f'//{MOVIE_INFO_PARENT_ELEMENT}[@id="{MOVIE_INFO_PARENT_ID}"]/{MOVIE_INFO_ELEMENT}[contains(@class, "{MOVIE_INFO_CLASS}")]'

ORIGINAL_TITLE_PARENT_TEXT = "Original title"
ORIGINAL_TITLE_PARENT_TEXT_SPANISH = "tulo original"
ORIGINAL_TITLE_PARENT_ELEMENT = "dt"
ORIGINAL_TITLE_ELEMENT = "dd"

ORIGINAL_TITLE_XPATH = f'./{ORIGINAL_TITLE_PARENT_ELEMENT}[contains(text(), "{ORIGINAL_TITLE_PARENT_TEXT}") or contains(text(), "{ORIGINAL_TITLE_PARENT_TEXT_SPANISH}")]/following-sibling::*[1][self::{ORIGINAL_TITLE_ELEMENT}]'
# Technical info is the movie-info section that starts with "Original title"
TECHNICAL_INFO_XPATH = f'{MOVIE_INFO_SECTIONS_XPATH}/{ORIGINAL_TITLE_XPATH}/parent::{MOVIE_INFO_ELEMENT}'

OTHER_TITLES_GRANDPARENT_CLASS = "akas"
OTHER_TITLES_GRANDPARENT_ELEMENT = "dd"
OTHER_TITLES_PARENT_ELEMENT = "ul"
OTHER_TITLES_ELEMENT = "li"

OTHER_TITLES_XPATH = f'./{OTHER_TITLES_GRANDPARENT_ELEMENT}[contains(@class, "{OTHER_TITLES_GRANDPARENT_CLASS}")]/' \
                     f'{OTHER_TITLES_PARENT_ELEMENT}/{OTHER_TITLES_ELEMENT}'

MOVIE_INFO_XPATH = f'//{MOVIE_INFO_PARENT_ELEMENT}[@id="{MOVIE_INFO_PARENT_ID}"]/{MOVIE_INFO_ELEMENT}[contains(@class, "{MOVIE_INFO_CLASS}")]/' \
                   f'{ORIGINAL_TITLE_XPATH}/parent::{MOVIE_INFO_ELEMENT}'


DATE_ELEMENT = "dd"
DATE_ATTRIBUTE_NAME = "itemprop"
DATE_ATTRIBUTE_VALUE = "datePublished"

DATE_XPATH = f'./{DATE_ELEMENT}[@{DATE_ATTRIBUTE_NAME}="{DATE_ATTRIBUTE_VALUE}"]'

DURATION_ELEMENT = "dd"
DURATION_ATTRIBUTE_NAME = "itemprop"
DURATION_ATTRIBUTE_VALUE = "duration"

DURATION_XPATH = f'./{DURATION_ELEMENT}[@{DURATION_ATTRIBUTE_NAME}="{DURATION_ATTRIBUTE_VALUE}"]'

COUNTRY_SIBLING_ELEMENT = "dt"
COUNTRY_SIBLING_TEXT = "Country"
COUNTRY_GRANDPARENT_ELEMENT = "dd"
COUNTRY_PARENT_ELEMENT = "span"
COUNTRY_PARENT_ID = "country-img"
COUNTRY_ELEMENT = "img"
COUNTRY_CLASS = "nflag"
COUNTRY_ATTRIBUTE = "alt"

COUNTRY_XPATH = f'./{COUNTRY_SIBLING_ELEMENT}[text()="{COUNTRY_SIBLING_TEXT}"]/following-sibling::*[1][self::{COUNTRY_GRANDPARENT_ELEMENT}]/' \
                f'{COUNTRY_PARENT_ELEMENT}[@id="{COUNTRY_PARENT_ID}"]/{COUNTRY_ELEMENT}[contains(@class, "{COUNTRY_CLASS}")]/@{COUNTRY_ATTRIBUTE}'

MOVIE_SAGA_SIBLING_ELEMENT = "dt"
MOVIE_SAGA_SIBLING_TEXT = "Movie Groups"
MOVIE_SAGA_GRANDPARENT_ELEMENT = "dd"
MOVIE_SAGA_PARENT_ELEMENT = "span"
MOVIE_SAGA_ELEMENT = "a"

MOVIE_SAGA_XPATH = f'./{MOVIE_SAGA_SIBLING_ELEMENT}[text()="{MOVIE_SAGA_SIBLING_TEXT}"]/following-sibling::*[1][self::{MOVIE_SAGA_GRANDPARENT_ELEMENT}]/' \
                    f'{MOVIE_SAGA_PARENT_ELEMENT}/{MOVIE_SAGA_ELEMENT}'

SYNOPSIS_SIBLING_ELEMENT = "dt"
SYNOPSIS_SIBLING_TEXT = "Synopsis"
SYNOPSIS_SIBLING_TEXT_SPANISH = "Sinopsis"
SYNOPSIS_ELEMENT = "dd"
SYNOPSIS_ATTRIBUTE = "itemprop"
SYNOPSIS_ATTRIBUTE_VALUE = "description"

SYNOPSIS_XPATH = f'.//{SYNOPSIS_SIBLING_ELEMENT}[contains(text(), "{SYNOPSIS_SIBLING_TEXT}") or contains(text(), "{SYNOPSIS_SIBLING_TEXT_SPANISH}")]/following-sibling::*[1][self::{SYNOPSIS_ELEMENT}][@{SYNOPSIS_ATTRIBUTE}="{SYNOPSIS_ATTRIBUTE_VALUE}"]'

EACH_GENRE_GRANDPARENT_ELEMENT = "dd"
EACH_GENRE_GRANDPARENT_CLASS = "card-genres"
EACH_GENRE_PARENT_ELEMENT = "span"
EACH_GENRE_PARENT_ATTRIBUTE_NAME = "itemprop"
EACH_GENRE_PARENT_ATTRIBUTE_VALUE = "genre"
EACH_GENRE_ELEMENT = "a"

#f'./{EACH_GENRE_GRANDPARENT_ELEMENT}[contains(@class, "{EACH_GENRE_GRANDPARENT_CLASS}")]/' \
EACH_GENRE_XPATH = f'.//{EACH_GENRE_PARENT_ELEMENT}[@{EACH_GENRE_PARENT_ATTRIBUTE_NAME}="{EACH_GENRE_PARENT_ATTRIBUTE_VALUE}"]/' \
                    f'{EACH_GENRE_ELEMENT}'

EACH_TOPIC_PARENT_ELEMENT = EACH_GENRE_GRANDPARENT_ELEMENT
EACH_TOPIC_PARENT_CLASS = EACH_GENRE_GRANDPARENT_CLASS
EACH_TOPIC_ELEMENT = "a"

EACH_TOPIC_XPATH = f'./{EACH_TOPIC_PARENT_ELEMENT}[contains(@class, "{EACH_TOPIC_PARENT_CLASS}")]/' \
                    f'{EACH_TOPIC_ELEMENT}'

DIRECTORS_WRAPPER_PARENT_CLASS = "directors"
DIRECTORS_WRAPPER_PARENT_ELEMENT = "dd"
DIRECTORS_WRAPPER_CLASS = "credits"
DIRECTORS_WRAPPER_ELEMENT = "div"

DIRECTORS_WRAPPER_XPATH = f'//{DIRECTORS_WRAPPER_PARENT_ELEMENT}[contains(@class, "{DIRECTORS_WRAPPER_PARENT_CLASS}")]/' \
                            f'{DIRECTORS_WRAPPER_ELEMENT}[contains(@class, "{DIRECTORS_WRAPPER_CLASS}")]'

EACH_DIRECTOR_GRANDPARENT_ATTRIBUTE_NAME = "itemprop"
EACH_DIRECTOR_GRANDPARENT_ATTRIBUTE_VALUE = "director"
EACH_DIRECTOR_GRANDPARENT_ELEMENT = "span"

EACH_DIRECTOR_ATTRIBUTE = "itemprop"
EACH_DIRECTOR_VALUE = "name"
EACH_DIRECTOR_ELEMENT = "span"

EACH_DIRECTOR_MORE_INFO_ELEMENT = "i"

EACH_DIRECTOR_GRANDPARENT_XPATH = f'./{EACH_DIRECTOR_GRANDPARENT_ELEMENT}[@{EACH_DIRECTOR_GRANDPARENT_ATTRIBUTE_NAME}="{EACH_DIRECTOR_GRANDPARENT_ATTRIBUTE_VALUE}"]'
DIRECTOR_XPATH = f'.//{EACH_DIRECTOR_ELEMENT}[@{EACH_DIRECTOR_ATTRIBUTE}="{EACH_DIRECTOR_VALUE}"]'
DIRECTOR_MORE_INFO_XPATH = f'./{EACH_DIRECTOR_MORE_INFO_ELEMENT}'

# GENERAL STAFF

SCREEN_WRITERS_TITLE = "Screenwriter"
MUSICIANS_TITLE = "Music"
CINEMATOGRAPHERS_TITLE = "Cinematography"
CAST_TITLE = "Cast"
PRODUCERS_TITLE = "Producer"
MOVIE_SAGA = "Movie Saga"

STAFF_PREVIOUS_SIBLING_ELEMENT = "dt"
STAFF_WRAPPER_PARENT_ELEMENT = "dd"
STAFF_WRAPPER_CLASS = "credits"
STAFF_WRAPPER_ELEMENT = "div"

GET_TECHNICAL_STAFF_WRAPPER_XPATH = lambda title: f'//{STAFF_PREVIOUS_SIBLING_ELEMENT}[text()="{title}"]/following-sibling::*[1][self::{STAFF_WRAPPER_PARENT_ELEMENT}]/' \
                                             f'{STAFF_WRAPPER_ELEMENT}[contains(@class, "{STAFF_WRAPPER_CLASS}")]'
GET_CAST_WRAPPER_XPATH = f'//{STAFF_PREVIOUS_SIBLING_ELEMENT}[text()="Cast"]/following-sibling::*[1][self::{STAFF_WRAPPER_PARENT_ELEMENT}]//' \
                                             f'{STAFF_WRAPPER_ELEMENT}[@class="cast-wrapper"]'

COUNTRIES_CO_PRODUCTION_CLASS = "card-producer"
COUNTRIES_CO_PRODUCTION_START_STR = "Co-production"
COUNTRIES_CO_PRODUCTION_SEPARATOR = "-"
COUNTRIES_CO_PRODUCTION_XPATH = f'//{STAFF_PREVIOUS_SIBLING_ELEMENT}[text()="{PRODUCERS_TITLE}"]/following-sibling::*[1][self::{STAFF_WRAPPER_PARENT_ELEMENT}][contains(@class, "{COUNTRIES_CO_PRODUCTION_CLASS}")]'

EACH_STAFF_INVALID_CLASS = "card-cast"
GET_INVALID_STAFF_XPATH = lambda title: f'//{STAFF_PREVIOUS_SIBLING_ELEMENT}[text()="{title}"]/following-sibling::*[1][self::{STAFF_WRAPPER_PARENT_ELEMENT}][contains(@class, "{EACH_STAFF_INVALID_CLASS}")]'

EACH_STAFF_PARENT_ELEMENT = "span"
EACH_STAFF_PARENT_CLASS = "nb"
EACH_STAFF_ELEMENT = "parent::a"#"span"
EACH_STAFF_LINK_ELEMENT = "a"

EACH_STAFF_PARENT_XPATH = f'.//{EACH_STAFF_PARENT_ELEMENT}[contains(@class, "{EACH_STAFF_PARENT_CLASS}")]'
EACH_ACTOR_PARENT_XPATH_ON_CARDS = f'.//li[contains(@itemprop, "actor")]/a/div[@class="name"]'
EACH_STAFF_XPATH = f'.//{EACH_STAFF_ELEMENT}'
EACH_STAFF_LINK_XPATH = f'./{EACH_STAFF_LINK_ELEMENT}/{EACH_STAFF_ELEMENT}'

EACH_STAFF_ROLE_PARENT_SIBLING_ELEMENT = "i"

EACH_STAFF_ROLE_PARENT_SIBLING_XPATH = f'./parent::{EACH_STAFF_PARENT_ELEMENT}/preceding-sibling::*[1][self::{EACH_STAFF_ROLE_PARENT_SIBLING_ELEMENT}]'
EACH_STAFF_LINK_ROLE_PARENT_SIBLING_XPATH = f'./parent::{EACH_STAFF_LINK_ELEMENT}/parent::{EACH_STAFF_PARENT_ELEMENT}/preceding-sibling::*[1][self::{EACH_STAFF_ROLE_PARENT_SIBLING_ELEMENT}]'

EACH_STAFF_XPATH_DICT = {
    SCREEN_WRITERS_TITLE: EACH_STAFF_XPATH,
    MUSICIANS_TITLE: EACH_STAFF_XPATH,
    CINEMATOGRAPHERS_TITLE: EACH_STAFF_XPATH,
    CAST_TITLE: EACH_STAFF_LINK_XPATH,
    PRODUCERS_TITLE: EACH_STAFF_XPATH,
}

EACH_STAFF_ROLE_XPATH = {
    SCREEN_WRITERS_TITLE: EACH_STAFF_ROLE_PARENT_SIBLING_XPATH,
    MUSICIANS_TITLE: EACH_STAFF_ROLE_PARENT_SIBLING_XPATH,
    CINEMATOGRAPHERS_TITLE: EACH_STAFF_ROLE_PARENT_SIBLING_XPATH,
    CAST_TITLE: EACH_STAFF_LINK_ROLE_PARENT_SIBLING_XPATH,
    PRODUCERS_TITLE: EACH_STAFF_ROLE_PARENT_SIBLING_XPATH,
}

ACCEPTABLE_INVALID_STAFF = {
    SCREEN_WRITERS_TITLE: (),
    MUSICIANS_TITLE: (),
    CINEMATOGRAPHERS_TITLE: ("Animation"),
    CAST_TITLE: ("Documentary", "Animation"),
    PRODUCERS_TITLE: ()
}

# FILM AFFINITY DETAILS

AWARDS_WRAPPER_SIBLING_ELEMENT = "dt"
AWARDS_WRAPPER_SIBLING_TEXT = "Awards"
AWARDS_WRAPPER_PARENT_ELEMENT = "dd"
AWARDS_WRAPPER_CLASS = "award"

AWARDS_WRAPPER_XPATH = f'//{AWARDS_WRAPPER_SIBLING_ELEMENT}[text()="{AWARDS_WRAPPER_SIBLING_TEXT}"]/following-sibling::*[1][self::{AWARDS_WRAPPER_PARENT_ELEMENT}][contains(@class, "{AWARDS_WRAPPER_CLASS}")]'

EACH_AWARD_ELEMENT = "div"
EACH_AWARD_YEAR_ELEMENT = "a"

EACH_AWARD_YEAR_XPATH = f'./{EACH_AWARD_ELEMENT}/{EACH_AWARD_YEAR_ELEMENT}'
EACH_AWARD_TEXT_XPATH = 'following-sibling::text()[1]'

# FILM AFFINITY INFO
RATING_PARENT_WRAPPER_ELEMENT = "div"
RATING_PARENT_WRAPPER_ID = "rat-avg-container"
RATING_ELEMENT = "div"
RATING_ID = "movie-rat-avg"
RATING_ITEMPROP = "ratingValue"

REVIEW_COUNT_ELEMENT = "meta"
REVIEW_COUNT_ITEMPROP = "reviewCount"

AMOUNT_OF_VOTES_PARENT_ELEMENT = "div"
AMOUNT_OF_VOTES_PARENT_ID = "movie-count-rat"
AMOUNT_OF_VOTES_ELEMENT = "span"
AMOUNT_OF_VOTES_ITEMPROP = "ratingCount"

RATING_WRAPPER_XPATH = f'//{RATING_PARENT_WRAPPER_ELEMENT}[contains(@id, "{RATING_PARENT_WRAPPER_ID}")]'
RATING_XPATH = f'./{RATING_ELEMENT}[contains(@id, "{RATING_ID}")][contains(@itemprop, "{RATING_ITEMPROP}")]/@content'
RATING_VOTES_XPATH = f'./{AMOUNT_OF_VOTES_PARENT_ELEMENT}[contains(@id, "{AMOUNT_OF_VOTES_PARENT_ID}")]/{AMOUNT_OF_VOTES_ELEMENT}[contains(@itemprop, "{AMOUNT_OF_VOTES_ITEMPROP}")]/@content'
REVIEWS_COUNT_XPATH = f'./{REVIEW_COUNT_ELEMENT}[contains(@itemprop, "{REVIEW_COUNT_ITEMPROP}")]/@content'

POSTER_PARENT_ELEMENT = "div"
POSTER_PARENT_ID = "movie-main-image-container"
POSTER_ELEMENT = "a"
POSTER_CHILD_ELEMENT = "img"

POSTER_XPATH = f'//{POSTER_PARENT_ELEMENT}[contains(@id, "{POSTER_PARENT_ID}")]/descendant::{POSTER_ELEMENT}//{POSTER_CHILD_ELEMENT}'

#LANGUAGES

LANG_TITLE_PARENT_ELEMENT = "h1"
LANG_TITLE_PARENT_ID = "main-title"
LANG_TITLE_ELEMENT = "span"
LANG_TITLE_ITEMPROP = "name"

LANG_TITLE_XPATH = f'//{LANG_TITLE_PARENT_ELEMENT}[contains(@id, "{LANG_TITLE_PARENT_ID}")]/{LANG_TITLE_ELEMENT}[contains(@itemprop, "{LANG_TITLE_ITEMPROP}")]'



# RELEVANT LINKS
RELEVANT_LINKS_SIBLING_ELEMENT = "div"
RELEVANT_LINKS_SIBLING_CLASS = "title"
RELEVANT_LINKS_SIBLING_TEXT = "Links"

RELEVANT_LINKS_GRANDPARENT_ELEMENT = "div"
RELEVANT_LINKS_GRANDPARENT_CLASS = "body"
RELEVANT_LINKS_PARENT_ELEMENT = "div"
RELEVANT_LINKS_ELEMENT = "a"

RELEVANT_LINKS_XPATH = f'//{RELEVANT_LINKS_SIBLING_ELEMENT}[contains(@class, "{RELEVANT_LINKS_SIBLING_CLASS}")][text()="{RELEVANT_LINKS_SIBLING_TEXT}"]/following-sibling::*[1][self::{RELEVANT_LINKS_GRANDPARENT_ELEMENT}][contains(@class, "{RELEVANT_LINKS_GRANDPARENT_CLASS}")]/{RELEVANT_LINKS_PARENT_ELEMENT}/{RELEVANT_LINKS_ELEMENT}'


# AVAILABLE AT
AVAILABLE_AT_WRAPPER_ELEMENT = "div"
AVAILABLE_AT_WRAPPER_ID = "stream-wrapper"

AVAILABLE_AT_WRAPPER_XPATH = f'//{AVAILABLE_AT_WRAPPER_ELEMENT}[contains(@id, "{AVAILABLE_AT_WRAPPER_ID}")]'

JUST_WATCH_PARENT_ELEMENT = "div"
JUST_WATCH_PARENT_CLASS = "justwatch-logo"
JUST_WATCH_ELEMENT = "a"

JUST_WATCH_URL_XPATH = f'./{JUST_WATCH_PARENT_ELEMENT}[contains(@class, "{JUST_WATCH_PARENT_CLASS}")]/{JUST_WATCH_ELEMENT}'

AVAILABLE_AT_WRAPPER_BODY_ELEMENT = "div"
AVAILABLE_AT_WRAPPER_BODY_CLASS = "body"

AVAILABLE_AT_WRAPPER_BODY_XPATH = f'./{AVAILABLE_AT_WRAPPER_BODY_ELEMENT}[contains(@class, "{AVAILABLE_AT_WRAPPER_BODY_CLASS}")]'

AVAILABLE_AT_WRAPPER_SIBLING_ELEMENT = "div"
AVAILABLE_AT_WRAPPER_SIBLING_CLASS = "sub-title"
PLATFORMS_WRAPPER_ELEMENT = "div"

FLATRATE_PLATFORMS_WRAPPER_SIBLING_TEXT = "flatrate"

FLATRATE_PLATFORMS_WRAPPER_XPATH = f'./{AVAILABLE_AT_WRAPPER_SIBLING_ELEMENT}[contains(@class, "{AVAILABLE_AT_WRAPPER_SIBLING_CLASS}")][text()="{FLATRATE_PLATFORMS_WRAPPER_SIBLING_TEXT}"]/following-sibling::*[1][self::{PLATFORMS_WRAPPER_ELEMENT}]'

BUY_PLATFORMS_WRAPPER_SIBLING_TEXT = "buy"

BUY_PLATFORMS_WRAPPER_XPATH = f'./{AVAILABLE_AT_WRAPPER_SIBLING_ELEMENT}[contains(@class, "{AVAILABLE_AT_WRAPPER_SIBLING_CLASS}")][text()="{BUY_PLATFORMS_WRAPPER_SIBLING_TEXT}"]/following-sibling::*[1][self::{PLATFORMS_WRAPPER_ELEMENT}]'

ADS_PLATFORMS_WRAPPER_SIBLING_TEXT = "ads"

ADS_PLATFORMS_WRAPPER_XPATH = f'./{AVAILABLE_AT_WRAPPER_SIBLING_ELEMENT}[contains(@class, "{AVAILABLE_AT_WRAPPER_SIBLING_CLASS}")][text()="{ADS_PLATFORMS_WRAPPER_SIBLING_TEXT}"]/following-sibling::*[1][self::{PLATFORMS_WRAPPER_ELEMENT}]'

RENT_PLATFORMS_WRAPPER_SIBLING_TEXT = "rent"

RENT_PLATFORMS_WRAPPER_XPATH = f'./{AVAILABLE_AT_WRAPPER_SIBLING_ELEMENT}[contains(@class, "{AVAILABLE_AT_WRAPPER_SIBLING_CLASS}")][text()="{RENT_PLATFORMS_WRAPPER_SIBLING_TEXT}"]/following-sibling::*[1][self::{PLATFORMS_WRAPPER_ELEMENT}]'

FREE_PLATFORMS_WRAPPER_SIBLING_TEXT = "free"

FREE_PLATFORMS_WRAPPER_XPATH = f'./{AVAILABLE_AT_WRAPPER_SIBLING_ELEMENT}[contains(@class, "{AVAILABLE_AT_WRAPPER_SIBLING_CLASS}")][text()="{FREE_PLATFORMS_WRAPPER_SIBLING_TEXT}"]/following-sibling::*[1][self::{PLATFORMS_WRAPPER_ELEMENT}]'

EACH_AVAILABLE_AT_ELEMENT = "a"

EACH_AVAILABLE_AT_XPATH = f'./{EACH_AVAILABLE_AT_ELEMENT}'

EACH_AVAILABLE_AT_PLATFORM_PARENT_ELEMENT = "div"
EACH_AVAILABLE_AT_PLATFORM_ELEMENT = "img"
EACH_AVAILABLE_AT_PLATFORM_ATTRIBUTE = "title"

EACH_AVAILABLE_AT_PLATFORM_DESCRIPTION_XPATH = f'./{EACH_AVAILABLE_AT_PLATFORM_PARENT_ELEMENT}/{EACH_AVAILABLE_AT_PLATFORM_ELEMENT}/@{EACH_AVAILABLE_AT_PLATFORM_ATTRIBUTE}'

PLATFORM_XPATH_BY_TYPE = {
    STREAMING: FLATRATE_PLATFORMS_WRAPPER_XPATH,
    RENT: RENT_PLATFORMS_WRAPPER_XPATH,
    BUY: BUY_PLATFORMS_WRAPPER_XPATH,
    FREE: FREE_PLATFORMS_WRAPPER_XPATH,
    ADS: ADS_PLATFORMS_WRAPPER_XPATH,
}

YOUTUBE_ID_REGEX = "vi\/([^\/]+)"